apiVersion: v1
kind: Namespace
metadata:
  name: aks-helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: aks-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS) - Hello World! through internal-pls-ingress with TLS"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: aks-helloworld
spec:
  type: ClusterIP # LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-helloworld
